//-----------------------------------------------------
//             Variables globales 
//-----------------------------------------------------
var productos = [
    { nombre: '"Harry Potter y la Piedra Filosofal"',            precio: 20000,   stock: 100,   editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Un niño descubre que es un mago y comienza su épica aventura en Hogwarts, enfrentando a Lord Voldemort. ',                                                         foto: 'img/HP01a.jpg',           envio: true,},
    { nombre: '"Harry Potter y la Cámara Secreta"',              precio: 21000,   stock: 99,    editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Harry desentraña los misterios de una siniestra cámara oculta en Hogwarts mientras lucha contra el heredero de Slytherin. ',                                       foto: 'img/HP02a.jpg',           envio: true,},
    { nombre: '"Harry Potter y el Prisionero de Azkaban"',       precio: 22000,   stock: 125,   editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Harry se entera del pasado de su padre y enfrenta a Sirius Black, mientras descubre la verdad sobre su conexión con el temible mago que lo persigue. ',            foto: 'img/HP03a.jpg',           envio: true,},
    { nombre: '"Harry Potter y el Cáliz de Fuego"',              precio: 23000,   stock: 150,   editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Harry participa en el Torneo de los Tres Magos y enfrenta peligros mortales, descubriendo una conspiración que lo llevará a un enfrentamiento con Voldemort. ',    foto: 'img/HP04a.jpg',           envio: true,},
    { nombre: '"Harry Potter y la Órden del Fénix"',             precio: 24000,   stock: 85,    editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Harry lidera a sus amigos en la lucha contra la opresión del Ministerio de Magia y se prepara para la batalla final contra Voldemort. ',                           foto: 'img/HP05a.jpg',           envio: true,},
    { nombre: '"Harry Potter y el Misterio del Principe"',       precio: 25000,   stock: 100,   editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Harry investiga el pasado de Voldemort con la ayuda del misterioso libro de texto de "El príncipe mestizo", mientras el Señor Oscuro intensifica sus planes. ',    foto: 'img/HP06a.jpg',           envio: true,},
    { nombre: '"Harry Potter y las Reliquias de la Muerte"',     precio: 26000,   stock: 150,   editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Harry, Hermione y Ron buscan las Horcruxes para destruir a Voldemort, enfrentando sacrificios y revelaciones en la culminación épica de la saga. ',                foto: 'img/HP07a.jpg',           envio: true,},
    { nombre: '"Harry Potter" Colección Completa en Castellano', precio: 80000,   stock: 50,    editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Colección completa de la Saga en Castellano. ',                                                                                                                    foto: 'img/HPcompesp01.jpg',     envio: true,},
    { nombre: '"Harry Potter" Colección Completa en Inglés',     precio: 80000,   stock: 15,    editorial: 'Salamandra',       categoria: 'Libros',       descripcion: ' Colección completa de la Saga en Inglés. ',                                                                                                                        foto: 'img/HPcompingl01.jpg',    envio: false,},
]